### ISSUE TITLE
file missing

### ISSUE THREAD

**Issue by bonbonx01** [szzexpoi/POEM#3]
when i run 'gqa_exp/train.py', and in the **line 72** of  'gqa_exp/DataLoader.py'. The file 'img_size.json' that this code is supposed to load dose not seem to be provided or generated.
Could you provide me with more information about this file? How should it be generated?
Thank you!

**Comment by szzexpoi** [comment]
Oh, I see. Sorry this is also related to something I generated for the previous projects. You can generate the file by iterating through all GQA images, and store their sizes as a dictionary (where the key is the image ID and the value is the corresponding [height, width]).

**Comment by bonbonx01** [comment]
ok! 
thank you ~
